# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergey/simple-mail

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergey/simple-mail

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	cd /home/sergey/simple-mail && $(CMAKE_COMMAND) -E cmake_progress_start /home/sergey/simple-mail/CMakeFiles /home/sergey/simple-mail/src/CMakeFiles/progress.marks
	cd /home/sergey/simple-mail && $(MAKE) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergey/simple-mail/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/sergey/simple-mail && $(MAKE) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/sergey/simple-mail && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/sergey/simple-mail && $(MAKE) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/sergey/simple-mail && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/CMakeFiles/SimpleMail2Qt5.dir/rule:
	cd /home/sergey/simple-mail && $(MAKE) -f CMakeFiles/Makefile2 src/CMakeFiles/SimpleMail2Qt5.dir/rule
.PHONY : src/CMakeFiles/SimpleMail2Qt5.dir/rule

# Convenience name for target.
SimpleMail2Qt5: src/CMakeFiles/SimpleMail2Qt5.dir/rule

.PHONY : SimpleMail2Qt5

# fast build rule for target.
SimpleMail2Qt5/fast:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/build
.PHONY : SimpleMail2Qt5/fast

# Convenience name for target.
src/CMakeFiles/SimpleMail2Qt5_autogen.dir/rule:
	cd /home/sergey/simple-mail && $(MAKE) -f CMakeFiles/Makefile2 src/CMakeFiles/SimpleMail2Qt5_autogen.dir/rule
.PHONY : src/CMakeFiles/SimpleMail2Qt5_autogen.dir/rule

# Convenience name for target.
SimpleMail2Qt5_autogen: src/CMakeFiles/SimpleMail2Qt5_autogen.dir/rule

.PHONY : SimpleMail2Qt5_autogen

# fast build rule for target.
SimpleMail2Qt5_autogen/fast:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5_autogen.dir/build.make src/CMakeFiles/SimpleMail2Qt5_autogen.dir/build
.PHONY : SimpleMail2Qt5_autogen/fast

SimpleMail2Qt5_autogen/mocs_compilation.o: SimpleMail2Qt5_autogen/mocs_compilation.cpp.o

.PHONY : SimpleMail2Qt5_autogen/mocs_compilation.o

# target to build an object file
SimpleMail2Qt5_autogen/mocs_compilation.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/SimpleMail2Qt5_autogen/mocs_compilation.cpp.o
.PHONY : SimpleMail2Qt5_autogen/mocs_compilation.cpp.o

SimpleMail2Qt5_autogen/mocs_compilation.i: SimpleMail2Qt5_autogen/mocs_compilation.cpp.i

.PHONY : SimpleMail2Qt5_autogen/mocs_compilation.i

# target to preprocess a source file
SimpleMail2Qt5_autogen/mocs_compilation.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/SimpleMail2Qt5_autogen/mocs_compilation.cpp.i
.PHONY : SimpleMail2Qt5_autogen/mocs_compilation.cpp.i

SimpleMail2Qt5_autogen/mocs_compilation.s: SimpleMail2Qt5_autogen/mocs_compilation.cpp.s

.PHONY : SimpleMail2Qt5_autogen/mocs_compilation.s

# target to generate assembly for a file
SimpleMail2Qt5_autogen/mocs_compilation.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/SimpleMail2Qt5_autogen/mocs_compilation.cpp.s
.PHONY : SimpleMail2Qt5_autogen/mocs_compilation.cpp.s

emailaddress.o: emailaddress.cpp.o

.PHONY : emailaddress.o

# target to build an object file
emailaddress.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/emailaddress.cpp.o
.PHONY : emailaddress.cpp.o

emailaddress.i: emailaddress.cpp.i

.PHONY : emailaddress.i

# target to preprocess a source file
emailaddress.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/emailaddress.cpp.i
.PHONY : emailaddress.cpp.i

emailaddress.s: emailaddress.cpp.s

.PHONY : emailaddress.s

# target to generate assembly for a file
emailaddress.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/emailaddress.cpp.s
.PHONY : emailaddress.cpp.s

mimeattachment.o: mimeattachment.cpp.o

.PHONY : mimeattachment.o

# target to build an object file
mimeattachment.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimeattachment.cpp.o
.PHONY : mimeattachment.cpp.o

mimeattachment.i: mimeattachment.cpp.i

.PHONY : mimeattachment.i

# target to preprocess a source file
mimeattachment.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimeattachment.cpp.i
.PHONY : mimeattachment.cpp.i

mimeattachment.s: mimeattachment.cpp.s

.PHONY : mimeattachment.s

# target to generate assembly for a file
mimeattachment.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimeattachment.cpp.s
.PHONY : mimeattachment.cpp.s

mimecontentformatter.o: mimecontentformatter.cpp.o

.PHONY : mimecontentformatter.o

# target to build an object file
mimecontentformatter.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimecontentformatter.cpp.o
.PHONY : mimecontentformatter.cpp.o

mimecontentformatter.i: mimecontentformatter.cpp.i

.PHONY : mimecontentformatter.i

# target to preprocess a source file
mimecontentformatter.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimecontentformatter.cpp.i
.PHONY : mimecontentformatter.cpp.i

mimecontentformatter.s: mimecontentformatter.cpp.s

.PHONY : mimecontentformatter.s

# target to generate assembly for a file
mimecontentformatter.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimecontentformatter.cpp.s
.PHONY : mimecontentformatter.cpp.s

mimefile.o: mimefile.cpp.o

.PHONY : mimefile.o

# target to build an object file
mimefile.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimefile.cpp.o
.PHONY : mimefile.cpp.o

mimefile.i: mimefile.cpp.i

.PHONY : mimefile.i

# target to preprocess a source file
mimefile.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimefile.cpp.i
.PHONY : mimefile.cpp.i

mimefile.s: mimefile.cpp.s

.PHONY : mimefile.s

# target to generate assembly for a file
mimefile.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimefile.cpp.s
.PHONY : mimefile.cpp.s

mimehtml.o: mimehtml.cpp.o

.PHONY : mimehtml.o

# target to build an object file
mimehtml.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimehtml.cpp.o
.PHONY : mimehtml.cpp.o

mimehtml.i: mimehtml.cpp.i

.PHONY : mimehtml.i

# target to preprocess a source file
mimehtml.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimehtml.cpp.i
.PHONY : mimehtml.cpp.i

mimehtml.s: mimehtml.cpp.s

.PHONY : mimehtml.s

# target to generate assembly for a file
mimehtml.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimehtml.cpp.s
.PHONY : mimehtml.cpp.s

mimeinlinefile.o: mimeinlinefile.cpp.o

.PHONY : mimeinlinefile.o

# target to build an object file
mimeinlinefile.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimeinlinefile.cpp.o
.PHONY : mimeinlinefile.cpp.o

mimeinlinefile.i: mimeinlinefile.cpp.i

.PHONY : mimeinlinefile.i

# target to preprocess a source file
mimeinlinefile.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimeinlinefile.cpp.i
.PHONY : mimeinlinefile.cpp.i

mimeinlinefile.s: mimeinlinefile.cpp.s

.PHONY : mimeinlinefile.s

# target to generate assembly for a file
mimeinlinefile.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimeinlinefile.cpp.s
.PHONY : mimeinlinefile.cpp.s

mimemessage.o: mimemessage.cpp.o

.PHONY : mimemessage.o

# target to build an object file
mimemessage.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimemessage.cpp.o
.PHONY : mimemessage.cpp.o

mimemessage.i: mimemessage.cpp.i

.PHONY : mimemessage.i

# target to preprocess a source file
mimemessage.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimemessage.cpp.i
.PHONY : mimemessage.cpp.i

mimemessage.s: mimemessage.cpp.s

.PHONY : mimemessage.s

# target to generate assembly for a file
mimemessage.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimemessage.cpp.s
.PHONY : mimemessage.cpp.s

mimemultipart.o: mimemultipart.cpp.o

.PHONY : mimemultipart.o

# target to build an object file
mimemultipart.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimemultipart.cpp.o
.PHONY : mimemultipart.cpp.o

mimemultipart.i: mimemultipart.cpp.i

.PHONY : mimemultipart.i

# target to preprocess a source file
mimemultipart.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimemultipart.cpp.i
.PHONY : mimemultipart.cpp.i

mimemultipart.s: mimemultipart.cpp.s

.PHONY : mimemultipart.s

# target to generate assembly for a file
mimemultipart.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimemultipart.cpp.s
.PHONY : mimemultipart.cpp.s

mimepart.o: mimepart.cpp.o

.PHONY : mimepart.o

# target to build an object file
mimepart.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimepart.cpp.o
.PHONY : mimepart.cpp.o

mimepart.i: mimepart.cpp.i

.PHONY : mimepart.i

# target to preprocess a source file
mimepart.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimepart.cpp.i
.PHONY : mimepart.cpp.i

mimepart.s: mimepart.cpp.s

.PHONY : mimepart.s

# target to generate assembly for a file
mimepart.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimepart.cpp.s
.PHONY : mimepart.cpp.s

mimetext.o: mimetext.cpp.o

.PHONY : mimetext.o

# target to build an object file
mimetext.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimetext.cpp.o
.PHONY : mimetext.cpp.o

mimetext.i: mimetext.cpp.i

.PHONY : mimetext.i

# target to preprocess a source file
mimetext.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimetext.cpp.i
.PHONY : mimetext.cpp.i

mimetext.s: mimetext.cpp.s

.PHONY : mimetext.s

# target to generate assembly for a file
mimetext.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/mimetext.cpp.s
.PHONY : mimetext.cpp.s

quotedprintable.o: quotedprintable.cpp.o

.PHONY : quotedprintable.o

# target to build an object file
quotedprintable.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/quotedprintable.cpp.o
.PHONY : quotedprintable.cpp.o

quotedprintable.i: quotedprintable.cpp.i

.PHONY : quotedprintable.i

# target to preprocess a source file
quotedprintable.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/quotedprintable.cpp.i
.PHONY : quotedprintable.cpp.i

quotedprintable.s: quotedprintable.cpp.s

.PHONY : quotedprintable.s

# target to generate assembly for a file
quotedprintable.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/quotedprintable.cpp.s
.PHONY : quotedprintable.cpp.s

sender.o: sender.cpp.o

.PHONY : sender.o

# target to build an object file
sender.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/sender.cpp.o
.PHONY : sender.cpp.o

sender.i: sender.cpp.i

.PHONY : sender.i

# target to preprocess a source file
sender.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/sender.cpp.i
.PHONY : sender.cpp.i

sender.s: sender.cpp.s

.PHONY : sender.s

# target to generate assembly for a file
sender.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/sender.cpp.s
.PHONY : sender.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/server.cpp.s
.PHONY : server.cpp.s

serverreply.o: serverreply.cpp.o

.PHONY : serverreply.o

# target to build an object file
serverreply.cpp.o:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/serverreply.cpp.o
.PHONY : serverreply.cpp.o

serverreply.i: serverreply.cpp.i

.PHONY : serverreply.i

# target to preprocess a source file
serverreply.cpp.i:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/serverreply.cpp.i
.PHONY : serverreply.cpp.i

serverreply.s: serverreply.cpp.s

.PHONY : serverreply.s

# target to generate assembly for a file
serverreply.cpp.s:
	cd /home/sergey/simple-mail && $(MAKE) -f src/CMakeFiles/SimpleMail2Qt5.dir/build.make src/CMakeFiles/SimpleMail2Qt5.dir/serverreply.cpp.s
.PHONY : serverreply.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... SimpleMail2Qt5"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... SimpleMail2Qt5_autogen"
	@echo "... SimpleMail2Qt5_autogen/mocs_compilation.o"
	@echo "... SimpleMail2Qt5_autogen/mocs_compilation.i"
	@echo "... SimpleMail2Qt5_autogen/mocs_compilation.s"
	@echo "... emailaddress.o"
	@echo "... emailaddress.i"
	@echo "... emailaddress.s"
	@echo "... mimeattachment.o"
	@echo "... mimeattachment.i"
	@echo "... mimeattachment.s"
	@echo "... mimecontentformatter.o"
	@echo "... mimecontentformatter.i"
	@echo "... mimecontentformatter.s"
	@echo "... mimefile.o"
	@echo "... mimefile.i"
	@echo "... mimefile.s"
	@echo "... mimehtml.o"
	@echo "... mimehtml.i"
	@echo "... mimehtml.s"
	@echo "... mimeinlinefile.o"
	@echo "... mimeinlinefile.i"
	@echo "... mimeinlinefile.s"
	@echo "... mimemessage.o"
	@echo "... mimemessage.i"
	@echo "... mimemessage.s"
	@echo "... mimemultipart.o"
	@echo "... mimemultipart.i"
	@echo "... mimemultipart.s"
	@echo "... mimepart.o"
	@echo "... mimepart.i"
	@echo "... mimepart.s"
	@echo "... mimetext.o"
	@echo "... mimetext.i"
	@echo "... mimetext.s"
	@echo "... quotedprintable.o"
	@echo "... quotedprintable.i"
	@echo "... quotedprintable.s"
	@echo "... sender.o"
	@echo "... sender.i"
	@echo "... sender.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... serverreply.o"
	@echo "... serverreply.i"
	@echo "... serverreply.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/sergey/simple-mail && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

